-- 权限数据迁移脚本
-- 将 roles 表的 permissions JSON 字段拆分到独立的 role_permissions 表
-- 创建时间：2026-01-05

USE bonus_system;

-- 1. 创建角色权限关联表
CREATE TABLE IF NOT EXISTS `role_permissions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
  `role_id` VARCHAR(50) NOT NULL COMMENT '角色ID',
  `permission` VARCHAR(100) NOT NULL COMMENT '权限标识',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UNIQUE KEY `uk_role_permission` (`role_id`, `permission`),
  INDEX `idx_role_id` (`role_id`),
  INDEX `idx_permission` (`permission`),
  CONSTRAINT `fk_role_permissions_role` FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='角色权限关联表';

-- 2. 迁移现有数据（将 JSON 数组拆分成多行）
-- 使用临时表处理 JSON 数组
INSERT INTO role_permissions (role_id, permission)
SELECT 
  r.id AS role_id,
  JSON_UNQUOTE(JSON_EXTRACT(r.permissions, CONCAT('$[', numbers.n, ']'))) AS permission
FROM roles r
CROSS JOIN (
  SELECT 0 AS n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 
  UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9
  UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14
  UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19
  UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24
  UNION ALL SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29
  UNION ALL SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34
  UNION ALL SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39
  UNION ALL SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44
  UNION ALL SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49
  UNION ALL SELECT 50 UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54
  UNION ALL SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59
  UNION ALL SELECT 60 UNION ALL SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL SELECT 64
  UNION ALL SELECT 65 UNION ALL SELECT 66 UNION ALL SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69
  UNION ALL SELECT 70 UNION ALL SELECT 71 UNION ALL SELECT 72 UNION ALL SELECT 73 UNION ALL SELECT 74
  UNION ALL SELECT 75 UNION ALL SELECT 76 UNION ALL SELECT 77 UNION ALL SELECT 78 UNION ALL SELECT 79
  UNION ALL SELECT 80 UNION ALL SELECT 81 UNION ALL SELECT 82 UNION ALL SELECT 83 UNION ALL SELECT 84
  UNION ALL SELECT 85 UNION ALL SELECT 86 UNION ALL SELECT 87 UNION ALL SELECT 88 UNION ALL SELECT 89
  UNION ALL SELECT 90 UNION ALL SELECT 91 UNION ALL SELECT 92 UNION ALL SELECT 93 UNION ALL SELECT 94
  UNION ALL SELECT 95 UNION ALL SELECT 96 UNION ALL SELECT 97 UNION ALL SELECT 98 UNION ALL SELECT 99
) AS numbers
WHERE JSON_EXTRACT(r.permissions, CONCAT('$[', numbers.n, ']')) IS NOT NULL
ON DUPLICATE KEY UPDATE permission = VALUES(permission);

-- 3. 验证数据迁移
-- 查看迁移后的数据统计
SELECT 
  '迁移统计' AS info,
  COUNT(DISTINCT role_id) AS role_count,
  COUNT(*) AS total_permissions,
  COUNT(DISTINCT permission) AS unique_permissions
FROM role_permissions;

-- 查看每个角色的权限数量
SELECT 
  r.id,
  r.name,
  COUNT(rp.permission) AS permission_count
FROM roles r
LEFT JOIN role_permissions rp ON r.id = rp.role_id
GROUP BY r.id, r.name
ORDER BY r.name;

-- 4. 备份原 permissions 字段（重命名而不是删除，以防需要回滚）
ALTER TABLE roles 
CHANGE COLUMN permissions permissions_backup JSON DEFAULT NULL COMMENT '权限列表（已迁移到 role_permissions 表）';

-- 如果确认数据无误，可以执行以下命令删除备份字段
-- ALTER TABLE roles DROP COLUMN permissions_backup;

-- 完成提示
SELECT '✓ 权限数据迁移完成！原 permissions 字段已重命名为 permissions_backup' AS status;
